Mac-Win/Toucheese-Android

- app/src/main/java/com/example/toucheeseapp/ui/screens/HomeScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/viewmodel/StudioViewModel.kt
- #23 
- 
- SearchBar 모서리 둥글게 변경
- SearchBar 화면이동시 초기화 로직 수정
근데 이 모서리는 어떻게 수정하죠? ㅋㅋ
> 23 fix searchbar 기능수정

- app/src/main/java/com/example/toucheeseapp/ui/components/BottomActionButtons.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/StudioDetailScreen.kt
- 장바구니, 바로예약 버튼 추가
- 클릭 시 현재 기능이 제한되기 때문에 토스트메시지로 표현
> 30 feat 상품 탭 화면 버튼 추가

- .idea/assetWizardSettings.xml
- app/src/main/java/com/example/toucheeseapp/data/network/RetrofitClient.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/AppBarImageComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/DatePickComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductOrderOptionComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/ProductOrderDetailScreen.kt
- app/src/main/res/drawable/calendar_24px.xml
- app/src/main/res/drawable/minus_24px.xml
- app/src/main/res/drawable/minus_icon.xml
- app/src/main/res/drawable/plus_24px.xml
- 이미지 앱바 구현
- 기준 인원 및 기준 가격 표기
- 인원수 표기
- 촬영날짜 텍스트 필드 표기 (다음 스프린트 때 DatePicker 구현예정)
-
> 28 - 상품 주문 상세 페이지 구현

- app/src/main/java/com/example/toucheeseapp/data/model/ReviewResponse.kt
- app/src/main/java/com/example/toucheeseapp/data/model/load_concept/ConceptResponse.kt
- app/src/main/java/com/example/toucheeseapp/data/model/load_concept/ConceptResponseItem.kt
- app/src/main/java/com/example/toucheeseapp/data/model/review_studio/StudioReviewResponse.kt
- app/src/main/java/com/example/toucheeseapp/data/model/review_studio/StudioReviewResponseItem.kt
- app/src/main/java/com/example/toucheeseapp/data/model/specific_review/ReviewResponse.kt
- app/src/main/java/com/example/toucheeseapp/data/model/studio_detail/Product.kt
- app/src/main/java/com/example/toucheeseapp/data/model/studio_detail/StudioDetailResponse.kt
- app/src/main/java/com/example/toucheeseapp/data/network/ToucheeseServer.kt
- app/src/main/java/com/example/toucheeseapp/data/repository/StudioRepository.kt
- 기존 API 이름 및 경로 변경
- 새로운 API 추가
> [Feat] retrofit 연결

- app/src/main/java/com/example/toucheeseapp/data/model/specific_review/ReviewResponse.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductListComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ReviewImageDialog.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ReviewItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ReviewListComponenet.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ReviewPhotoComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/StudioInfoComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/Screen.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/HomeScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/ReviewDetailScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/StudioDetailScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/viewmodel/StudioViewModel.kt
> 40 fix 임시데이터 본 데이터로 수정

- app/src/main/java/com/example/toucheeseapp/data/model/product_detail/AddOption.kt
- app/src/main/java/com/example/toucheeseapp/data/model/product_detail/ProductDetailResponse.kt
- app/src/main/java/com/example/toucheeseapp/data/network/ToucheeseServer.kt
- app/src/main/java/com/example/toucheeseapp/data/repository/StudioRepository.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/AppBarImageComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductListComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductOrderOptionComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ReviewItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/Screen.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/ProductOrderDetailScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/StudioDetailScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/StudioListScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/viewmodel/StudioViewModel.kt
> 39 feat 화면 흐름 연결 및 데이터 연결

- app/src/main/java/com/example/toucheeseapp/ui/components/ShareBottomSheetComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/ReviewDetailScreen.kt
바텀시트 버튼 이벤트 활성화
리뷰 댓글 부분은 데이터가 없어서 수정 불가
> 43 fix 바텀시트 버튼 이벤트 및 리뷰 댓글 부분 수정

- app/src/main/java/com/example/toucheeseapp/ui/components/AppBarImageComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ImageSliderComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductOrderOptionComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ReviewListComponenet.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/Screen.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/ProductOrderDetailScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/StudioDetailScreen.kt
화면 수정
- 가격 1,000원 단위로 분리
- 이미지 높이 조정
-
> 44 UI 화면 수정

- app/src/main/java/com/example/toucheeseapp/ui/components/ProductOrderOptionComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/ProductOrderDetailScreen.kt
- 인원 수 조정
- 추가옵션 다중선택
- 추가옵션 선택시 최종가격 변경
> 47 feat 상품주문상세화면productorderdetailscreen 기능 추가

- app/src/main/java/com/example/toucheeseapp/ui/components/ShareBottomSheetComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/ReviewDetailScreen.kt
- fillMaxHeight()으로 하단까지 채우도록 설정함
> [UI] 바텀시트 하단까지 채우도록 설정

- app/src/main/java/com/example/toucheeseapp/ui/components/ProductItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ReviewImageDialog.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/StudioInfoComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/StudioDetailScreen.kt
> 54 fix 이미지 다이얼로그 수정 및 스튜디오 소개 수정

- .idea/deploymentTargetSelector.xml
- app/src/main/java/com/example/toucheeseapp/ui/components/CartItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/CartTopAppBarComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/StudioInfoComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/CartScreen.kt
해당 이슈와 관련없음 
새로 이슈파서 다시 해야함 
[fix] 공지사항 펼치기/접기 버튼 추가
> 56 feat 장바구니 화면 구현

- app/src/main/java/com/example/toucheeseapp/ui/components/CartItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/CartItemListComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/OptionChangeBottomSheetComponent.kt
> 59 feat 장바구니 화면 생성

- app/build.gradle.kts
- app/src/main/java/com/example/toucheeseapp/ui/components/DatePickComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/calendar/custom_datepicker_component.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/textfield/textfield_outlined_component.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/login/LoginScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/ProductOrderDetailScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/StudioDetailScreen.kt
> [UI] custom calendar screen

- app/src/main/java/com/example/toucheeseapp/ui/components/OrderPayMyInfoComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/OrderPayProductItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/OrderPayProductListComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/OrderPayTopAppBarComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/SectionTitle.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/OrderPayScreen.kt
> 68 UI 주문 결제 화면

- app/src/main/java/com/example/toucheeseapp/data/model/calendar_studio/CalendarTimeResponse.kt
- app/src/main/java/com/example/toucheeseapp/data/model/calendar_studio/CalendarTimeResponseItem.kt
- app/src/main/java/com/example/toucheeseapp/data/model/login/Login.kt
- app/src/main/java/com/example/toucheeseapp/data/model/reservation/ProductReservation.kt
- app/src/main/java/com/example/toucheeseapp/data/model/reservation/TimeReservation.kt
- app/src/main/java/com/example/toucheeseapp/data/model/studio_detail/OperationiHours.kt
- app/src/main/java/com/example/toucheeseapp/data/network/LoginService.kt
- app/src/main/java/com/example/toucheeseapp/data/network/RetrofitClient.kt
- app/src/main/java/com/example/toucheeseapp/data/network/ToucheeseServer.kt
- app/src/main/java/com/example/toucheeseapp/data/repository/LoginRepository.kt
- app/src/main/java/com/example/toucheeseapp/data/repository/StudioRepository.kt
- app/src/main/java/com/example/toucheeseapp/data/token_manager/TokenManager.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/OptionChangeBottomSheetComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductOrderOptionComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/login/LoginScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/ProductOrderDetailScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/viewmodel/LoginViewModel.kt
- app/src/main/java/com/example/toucheeseapp/ui/viewmodel/StudioViewModel.kt
- #71 
- 로그인 API
- 예약 API
- 캘린더 API
> [Feat] api 연결

- app/src/main/java/com/example/toucheeseapp/data/model/login/LoginResponseBody.kt
- app/src/main/java/com/example/toucheeseapp/data/network/LoginService.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/login/LoginScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/viewmodel/LoginViewModel.kt
- #75 
- [Fix] 로그인 API 수정
- [Fix] 로그인 로직 수정
- [Fix] 화면전환 로직 수정
- [Fix] 로그인 화면에서 login 버튼 클릭 시 키보드 바로 내려가도록 수정
> [Fix] 로그인 두 번 클릭시 작동하는 오류 수정

- app/src/main/java/com/example/toucheeseapp/data/model/carts_list/CartItemList.kt
- app/src/main/java/com/example/toucheeseapp/data/model/carts_optionChange/ChangedCartItem.kt
- app/src/main/java/com/example/toucheeseapp/data/model/saveCartData/CartData.kt
- app/src/main/java/com/example/toucheeseapp/data/model/saveCartData/TimeReservation.kt
- app/src/main/java/com/example/toucheeseapp/data/model/saveReservationData/CreateTime.kt
- app/src/main/java/com/example/toucheeseapp/data/model/saveReservationData/ReservationData.kt
- app/src/main/java/com/example/toucheeseapp/data/network/ToucheeseServer.kt
- app/src/main/java/com/example/toucheeseapp/data/repository/StudioRepository.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/ProductOrderDetailScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/viewmodel/StudioViewModel.kt
- #81 
모두 Header에 토큰 필요함
- [PUT] 장바구니 옵션 및 인원 변경  ( v1/members/carts/{cartId} )
- [DELETE] 해당 장바구니 삭제  ( v1/members/carts/{cartId} )
- [POST] 예약 정보 저장 기능  ( v1/members/reservations )
- [GET] 장바구니 목록 조회(회) ( v1/members/carts/list )
- [GET] 회원 정보 ( v1/members/infos )
> 81 feat | fix 데이터 api 수정

- app/src/main/java/com/example/toucheeseapp/ui/components/CartItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/CartTopAppBarComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/OptionChangeBottomSheetComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/CartScreen.kt
#85 
해당 화면에 필요없는 아이콘, 버튼들 
showReviewButton,
showDeleteIcon,
showOptionChangeButton 
false로 처리 해당 화면에 나타나지 않도록 수정
> 85 fix 장바구니 아이콘 삭제

- app/src/main/java/com/example/toucheeseapp/ui/components/CartItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/OptionChangeBottomSheetComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/OrderPayProductItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/ProductOrderOptionComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/calendar/CustomDatePickerComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/login/LoginScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/CartScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/OrderPayScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/ProductOrderDetailScreen.kt
- [상품 상세 조회 화면] 에서 촬영일자 선택 안 해도 화면 넘어가는 문제
- [장바구니 화면] 에서 장바구니 내역이 없어도 **[주문 및 결제 화면]**으로 넘어가는 문제
- [장바구니 화면] 에서 옵션 수정 시 바텀 내비 바가 그대로 보이는 문제
- [장바구니 화면] UI 수정 (패딩 등의 간격 조절 및 색상 조절)
- [주문 및 결제 화면] 에서 결제 수단 선택 안 해도 화면 넘어가는 문제
- [장바구니 화면] ModalBottomSheet UI 수정
- [주문 및 결제 화면] 상품 리스트 UI 수정
> [Fix] 버그 수정

- app/src/main/java/com/example/toucheeseapp/MainActivity.kt
- app/src/main/java/com/example/toucheeseapp/data/repository/QnaRepository.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/BottomNavBarComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/listitem/InfoListItemComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/listitem/InfoListitemComponent_NoChip.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/textbutton/IconButtonComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/components/topbar/TopAppBarComponent.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/Screen.kt
- app/src/main/java/com/example/toucheeseapp/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/CartScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/OrderPayScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Home/StudioListScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Qna/QNAScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Qna/QnaContentScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Qna/QnaScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/screens/tab_Qna/QnaWriteScreen.kt
- app/src/main/java/com/example/toucheeseapp/ui/theme/Color.kt
- app/src/main/java/com/example/toucheeseapp/ui/theme/Theme.kt
- app/src/main/java/com/example/toucheeseapp/ui/theme/Type.kt
- app/src/main/java/com/example/toucheeseapp/ui/viewmodel/QnaViewModel.kt
- #92 내 정보 문의 화면 구현
- 내정보-문의
- 내정보-문의내역
- 내정보-문의하기
- 카메라, 앨범 기능
> [UI | Feat] 내 정보 문의 화면 구현

- app/src/main/java/com/toucheese/app/ui/components/AppBarImageComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/ProductOrderOptionComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/SquareRadioButton.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/CartScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/ProductOrderDetailScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/StudioProductReviewScreen.kt
해당 이슈 화면 전체적인 테마 수정 및 디자인 수정
라디오 버튼 커스텀 추가
> 101 UI 앱 테마 수정

- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/StudioProductReviewScreen.kt
> [Style] import 경로 수정

- app/src/main/java/com/toucheese/app/data/model/qna/load_qnadetail/AnswerResponse.kt
- app/src/main/java/com/toucheese/app/data/model/qna/load_qnadetail/QnaDetailResponse.kt
- app/src/main/java/com/toucheese/app/data/model/qna/load_qnalist/Pageable.kt
- app/src/main/java/com/toucheese/app/data/model/qna/load_qnalist/QnaListItem.kt
- app/src/main/java/com/toucheese/app/data/model/qna/load_qnalist/QnaListResponse.kt
- app/src/main/java/com/toucheese/app/data/model/qna/load_qnalist/SortX.kt
- app/src/main/java/com/toucheese/app/data/model/qna/update_qnadetail/UpdateQnaBody.kt
- app/src/main/java/com/toucheese/app/data/model/qna/write_qnadetail/QnaDetailBody.kt
- app/src/main/java/com/toucheese/app/data/network/QnaService.kt
- app/src/main/java/com/toucheese/app/data/repository/LoginRepository.kt
- app/src/main/java/com/toucheese/app/data/repository/QnaRepository.kt
- app/src/main/java/com/toucheese/app/ui/components/listitem/InfoListItemComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/listitem/InfoListitemComponent_NoChip.kt
- app/src/main/java/com/toucheese/app/ui/navigation/Screen.kt
- app/src/main/java/com/toucheese/app/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Qna/QnaContentScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Qna/QnaScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Qna/QnaWriteScreen.kt
- app/src/main/java/com/toucheese/app/ui/viewmodel/QnaViewModel.kt
- #113 
- 문의하기 글 작성
- 문의하기 글 조회
- 문의하기 글 전체 조회
> [feat] 문의하기 기능 연결

- app/src/main/java/com/toucheese/app/ui/components/AppBarImageComponent.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/HomeScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/ProductOrderDetailScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/StudioListScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/StudioProductReviewScreen.kt
- #119 
- 카드에 아래 기능이 추가 되어있으나 현재 다른 화면에서도 사용하는 컴포넌트이므로 나중에 한 번에 수정하겠음
- 현재 적용 화면
> [UI] 스튜디오 주문 상세 옵션변경 화면 디자인 적용

- app/src/main/java/com/toucheese/app/data/model/home/carts_list/CartListResponseItem.kt
- app/src/main/java/com/toucheese/app/data/network/HomeService.kt
- app/src/main/java/com/toucheese/app/data/repository/HomeRepository.kt
- app/src/main/java/com/toucheese/app/ui/components/CartItemComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/OptionChangeBottomSheetComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/OrderPayMyInfoComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/OrderPayProductListComponent.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/CartScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/OrderPayScreen.kt
- app/src/main/java/com/toucheese/app/ui/viewmodel/HomeViewModel.kt
- #121 
- 장바구니 화면 디자인 적용
- 주문 및 결제 화면 디자인 적용
> [UI] 장바구니 및 주문 결제 디자인 적용

- app/src/main/java/com/toucheese/app/ui/components/ProductItemComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/ProductListComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/ReviewContent.kt
- app/src/main/java/com/toucheese/app/ui/components/ReviewImageDialog.kt
- app/src/main/java/com/toucheese/app/ui/components/ReviewListComponenet.kt
- app/src/main/java/com/toucheese/app/ui/components/ReviewPhotoComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/ReviewStudioInfoAndCommentComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/ShareBottomSheetComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/StudioTopAppBarComponent.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/ReviewDetailScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/StudioDetailScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/StudioProductReviewScreen.kt
#125 해당 이슈 수정
- 이미지 크기 수정 해당 피그마와 크기 같음
> 125 UI 리뷰 화면 수정

- app/src/main/java/com/toucheese/app/data/model/qna/load_qnadetail/AnswerResponse.kt
- app/src/main/java/com/toucheese/app/data/model/qna/load_qnadetail/QnaDetailResponse.kt
- app/src/main/java/com/toucheese/app/data/model/qna/load_qnalist/QnaListItem.kt
- app/src/main/java/com/toucheese/app/data/model/qna/load_qnalist/QnaListResponse.kt
- app/src/main/java/com/toucheese/app/data/network/QnaService.kt
- app/src/main/java/com/toucheese/app/data/repository/QnaRepository.kt
- app/src/main/java/com/toucheese/app/ui/components/TimeSlotButtonComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/listitem/InfoListItemComponent.kt
- app/src/main/java/com/toucheese/app/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Qna/QnaContentScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Qna/QnaScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Qna/QnaWriteScreen.kt
- app/src/main/java/com/toucheese/app/ui/viewmodel/QnaViewModel.kt
- 문의 작성 시 서버에 데이터 전송 안 되던 문제 해결
- 문의 작성 시 이미지 업로드 안 되던 문제 해결
> [Bug] 문의 작성 오류 수정

- .idea/other.xml
- app/src/main/java/com/toucheese/app/ui/components/StudioInfoComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/StudioListItemComponent.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/StudioListScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Qna/QnaScreen.kt
- 별점 Chip 화면에서 깨지는 문제 수정
- 별점이 0점일 경우 화면에 안 보여지도록 수정
- 별점이 0점일 경우 화면에 안 보여지도록 수정
> [UI] 스튜디오 조회 및 상세 조회 UI 수정

- app/build.gradle.kts
- app/src/main/java/com/toucheese/app/data/model/TokenAuthenticator.kt
- app/src/main/java/com/toucheese/app/data/model/home/studio_detail/StudioDetailResponse.kt
- app/src/main/java/com/toucheese/app/data/model/token/TokenRequest.kt
- app/src/main/java/com/toucheese/app/data/model/token/TokenResponse.kt
- app/src/main/java/com/toucheese/app/data/network/RetrofitClient.kt
- app/src/main/java/com/toucheese/app/data/network/TokenApi.kt
- app/src/main/java/com/toucheese/app/data/network/TokenApiModule.kt
- app/src/main/java/com/toucheese/app/data/token_manager/TokenManager.kt
- app/src/main/java/com/toucheese/app/ui/components/StudioInfoComponent.kt
#129 토큰 갱신 함수
- 토큰 갱신에 필요한 Api, Module 추가 
- 서버로부터 RefreshToken과 deviceId를 통한 토큰 갱신
> 129 feat 토큰 갱신

- .idea/deploymentTargetSelector.xml
- app/src/main/java/com/toucheese/app/ui/components/AppBarImageComponent.kt
- app/src/main/java/com/toucheese/app/ui/components/StudioInfoComponent.kt
- app/src/main/java/com/toucheese/app/ui/navigation/ToucheeseApp.kt
- app/src/main/java/com/toucheese/app/ui/screens/login/LoginScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/CartScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_Home/ProductOrderDetailScreen.kt
- app/src/main/java/com/toucheese/app/ui/screens/tab_myInfo/MyInfoScreen.kt
- [Fix] 상품 선택 삭제 시 예약 버튼 활성화 되어 있는 문제 수정
- [Fix] 상품 주문시 장바구니 아이템 바로 불러오도록 수정
- [Feat] 내 정보 화면 -> 예약한 스튜디오 리스트 클릭 시 예약일정 탭으로 이동
- [UI] StudioDetailScreen 별점 Chip 모양 수정 & 공지사항 데이터 없을 경우 삭제
- [Fix] LoginScreen LazyColumn 적용
- [UI] AppBarImageComponent 이미지 크기 수정
> [BUG] 버그 수정
